version: "3"
services:
  app:
    build: .
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.enchantertain.entrypoints=websecure"
      - "traefik.http.routers.enchantertain.rule=Host(`enchantertain.com`) || Host(`www.enchantertain.com`)"
      - "traefik.http.middlewares.enchantertain-redirect.redirectregex.regex=^https://enchantertain.com/(.*)"
      - "traefik.http.middlewares.enchantertain-redirect.redirectregex.replacement=https://www.enchantertain.com/$${1}"
      - "traefik.http.routers.enchantertain.tls.certresolver=lets-encr"
      - "traefik.http.routers.enchantertain.middlewares=enchantertain-redirect"
      - "traefik.http.routers.enchantertain.middlewares=enchantertain-auth"
      - "traefik.http.middlewares.enchantertain-auth.basicauth.users=enchantertain:$$apr1$$2mv0jkz7$$6.irxqUQgGQRP9lujr/Pc0"
    networks:
      - internal
      - proxy
networks:
  proxy:
    external: true
  internal:
    external: false
