version: "3"
services:
  app:
    build: .
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.find-similar-games.entrypoints=websecure"
      - "traefik.http.routers.find-similar-games.rule=Host(`find-similar-games.pascalkraupner.dev`)"
      - "traefik.http.routers.find-similar-games.tls.certresolver=lets-encr"
    networks:
      - internal
      - proxy
networks:
  proxy:
    external: true
  internal:
    external: false
