version: "3"
services:
  app:
    build: .
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.find-similar-games.entrypoints=websecure"
      - "traefik.http.routers.find-similar-games.rule=Host(`find-similar-games.pascalkraupner.dev`)"
      - "traefik.http.routers.find-similar-games.tls.certresolver=lets-encr"
      - "traefik.http.routers.find-similar-games.middlewares=find-similar-games-auth"
      - "traefik.http.middlewares.find-similar-games-auth.basicauth.users=pascal:$$apr1$$2/xHwJU3$$iqhuvn3Se1sNoZ0beuFMi1"
    networks:
      - internal
      - proxy
networks:
  proxy:
    external: true
  internal:
    external: false
